# Generated by Django 5.2.5 on 2025-08-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default='Student', max_length=100)),
                ('l_name', models.CharField(default='Student', max_length=100)),
                ('age', models.IntegerField()),
                ('level', models.CharField(choices=[('1', 'level One'), ('2', 'level Two'), ('3', 'level Three'), ('4', 'level Four')], max_length=20)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.BooleanField(default=True)),
                ('report', models.TextField(blank=True, max_length=300)),
            ],
        ),
    ]
