# Generated by Django 5.2.4 on 2025-08-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50, verbose_name='الاسم الأول')),
                ('l_name', models.CharField(max_length=50, verbose_name='الاسم الأخير')),
                ('age', models.IntegerField(verbose_name='العمر')),
                ('level', models.CharField(max_length=10, verbose_name='المرحلة الجامعية')),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='المعدل')),
                ('status', models.BooleanField(default=True, verbose_name='منتظم')),
                ('report', models.TextField(blank=True, null=True, verbose_name='ملاحظة')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
            },
        ),
    ]
