# Generated by Django 5.2.4 on 2025-08-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50, verbose_name='الاسم الأول')),
                ('l_name', models.CharField(max_length=50, verbose_name='الاسم الأخير')),
                ('age', models.IntegerField(verbose_name='العمر')),
                ('specialty', models.CharField(max_length=100, verbose_name='التخصص')),
                ('years_of_experience', models.IntegerField(verbose_name='سنوات الخبرة')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'معلم',
                'verbose_name_plural': 'المعلمين',
            },
        ),
    ]
