# Generated by Django 4.2 on 2025-08-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='file_report',
            field=models.FileField(blank=True, null=True, upload_to='files/%y/%m/%d', verbose_name='ملف التقرير'),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y/%m/%d', verbose_name='الصورة الشخصية'),
        ),
    ]
