# Generated by Django 4.2 on 2025-09-07 00:02

import django.core.validators
from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_file_report_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='f_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='الاسم الأول يجب أن يبدأ بحرف Capital ويحتوي على أحرف فقط.', regex='^[A-Z][a-zA-Z]*$')], verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y/%m/%d', validators=[students.validators.validate_image_mimetype], verbose_name='الصورة الشخصية'),
        ),
    ]
