# Generated by Django 5.2.4 on 2025-08-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المادة')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='كود المادة')),
                ('level', models.CharField(choices=[('1', 'الأولى'), ('2', 'الثانية'), ('3', 'الثالثة'), ('4', 'الرابعة'), ('5', 'الخامسة')], max_length=1, verbose_name='المستوى')),
                ('credit_hours', models.IntegerField(verbose_name='عدد الساعات المعتمدة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المادة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مادة دراسية',
                'verbose_name_plural': 'المواد الدراسية',
                'ordering': ['level', 'name'],
            },
        ),
    ]
